AWSTemplateFormatVersion: '2010-09-09'
Description: 'Complete AWS infrastructure for postgis-property-search-demo-py - pg_route and PostGIS learning environment'

Parameters:
  ProjectName:
    Type: String
    Default: postgis-property-search-demo-py
    Description: Name of the project for resource naming
    
  Environment:
    Type: String
    Default: development
    AllowedValues: [development, staging, production]
    Description: Environment for deployment
    
  DatabaseInstanceType:
    Type: String
    Default: db.t3.medium
    AllowedValues: 
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
      - db.t3.large
      - db.m6i.large
      - db.m6i.xlarge
      - db.r6g.large
      - db.r6g.xlarge
    Description: Database instance type
    
  DatabaseName:
    Type: String
    Default: pgroute_db
    Description: PostgreSQL database name
    
  DatabaseUsername:
    Type: String
    Default: postgres
    Description: PostgreSQL master username
    
  DatabasePassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: PostgreSQL master password (minimum 8 characters)

Resources:
  # VPC Stack
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment

  # Security Stack  
  SecurityStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: security.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        VPCCidr: !GetAtt VPCStack.Outputs.VPCCidr

  # Database Stack
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [VPCStack, SecurityStack]
    Properties:
      TemplateURL: database.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        DatabaseType: RDS
        DatabaseInstanceType: !Ref DatabaseInstanceType
        DatabaseName: !Ref DatabaseName
        DatabaseUsername: !Ref DatabaseUsername
        DatabasePassword: !Ref DatabasePassword
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PrivateSubnetIds: !GetAtt VPCStack.Outputs.PrivateSubnetIds
        DatabaseSecurityGroupId: !GetAtt SecurityStack.Outputs.DatabaseSecurityGroupId

  # Monitoring Stack
  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DatabaseStack
    Properties:
      TemplateURL: monitoring.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        DatabaseIdentifier: !GetAtt DatabaseStack.Outputs.DatabaseIdentifier

Outputs:
  VPCId:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VPCId
    Export:
      Name: !Sub '${AWS::StackName}-VPCId'
      
  DatabaseEndpoint:
    Description: Database endpoint
    Value: !GetAtt DatabaseStack.Outputs.DatabaseEndpoint
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseEndpoint'
      
  DatabasePort:
    Description: Database port
    Value: !GetAtt DatabaseStack.Outputs.DatabasePort
    Export:
      Name: !Sub '${AWS::StackName}-DatabasePort'
      
  AlertsTopicArn:
    Description: SNS topic for alerts
    Value: !GetAtt MonitoringStack.Outputs.AlertsTopicArn
    Export:
      Name: !Sub '${AWS::StackName}-AlertsTopicArn'